# Generated by Django 3.0.8 on 2020-08-16 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='image',
        ),
    ]
