# Generated by Django 3.0.8 on 2020-08-16 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_content_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='body',
            new_name='link',
        ),
    ]
