# Generated by Django 3.0.8 on 2020-08-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20200816_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.ImageField(default='media/test_img.jpg', upload_to=''),
        ),
    ]
