# Generated by Django 3.0.8 on 2020-08-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20200816_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='test_img.jpg', upload_to=''),
        ),
    ]
